### ISSUE TITLE
Cantidad de players.

### ISSUE THREAD

**Issue by brivalio** [SmileYzn/PugMod-AMXX#15]
Buenas Smileyzn, tengo un problema con la cantidad de usuarios para iniciar la partida. En la config dice 10 min y 10 max, pero estando en el juego elige 6 para cada lado. Como podria solucionarlo?
Gracias desde ya

**Comment by SmileYzn** [comment]
More than 5 players are in teams, when captain is picking players?

**Comment by brivalio** [comment]
Exactly, the captain can pick more than 5 players for his team

**Comment by SmileYzn** [comment]
I will check and fix it!

**Comment by brivalio** [comment]
Thank you very much!!

**Comment by SmileYzn** [comment]
Fixed in [2f0fdb4](https://github.com/SmileYzn/PugMod/commit/2f0fdb456869ce20b27bc363d5880477dba3da6f)

You can test to close issue? Thanks

**Comment by brivalio** [comment]
Ok, i will test it!

**Comment by SmileYzn** [comment]
Ps. I changed whole mod to use reapi, so i will make these changes on next release
