### ISSUE TITLE
Ban with AMXBans

### ISSUE THREAD

**Issue by illiaKuryaki** [SmileYzn/PugMod-AMXX#16]
Hi SmileY, is there any chance to have possibility to get people banned with amxbans ? (if present) so we can have a web "log" about who quit the pug server.

AMXBans GM 1.6 Syntax : amx_banip "time in mins" "steamID or nickname or #authid or IP" "reason"

Best

**Comment by SmileYzn** [comment]
I will make a editable string on next release, for now you can edit the code

Ps. I changed whole mod to use reapi, so i will make these changes on next release

**Comment by illiaKuryaki** [comment]
Awesome, thanks !

**Comment by illiaKuryaki** [comment]
Hi, sorry to ask again, did you have any ETA on next release ? Thanks

**Comment by SmileYzn** [comment]
Today i guess

**Comment by illiaKuryaki** [comment]
Sorry to bother you again with this xD, but i been trying to edit the string, but since i am not a coder, is not working xD, i show you what i have and maybe you can give me a idea what i am doing wrong ? thanks in advance :

Line 169 at PugCore.sma

`server_cmd("amx_ban %i %s 'Quitear MIX en curso no esta permitido'",iBanTime,szAuth);`

**Comment by SmileYzn** [comment]
amx_ban will not work on disconnected players, i think that amx_addban will work.

Also: server_cmd("amx_ban %i ^"%s"^ 'Quitear MIX en curso no esta permitido'",iBanTime,szAuth);

**Comment by illiaKuryaki** [comment]
Hi, i try with the line you givme, but i get errors when i try to compile it :

```
AMX Mod X Compiler 1.10.0.5406
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2013 AMX Mod X Team

PugCore.sma(169) : error 027: invalid character constant
PugCore.sma(169) : error 017: undefined symbol "uitear"
PugCore.sma(169) : error 029: invalid expression, assumed zero
PugCore.sma(169) : fatal error 107: too many error messages on one line

Compilation aborted.
4 Errors.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

If i try with the line i got and amx_addban, it compiles, but the ban is not well placed :

```
Dropped bL' from server
Reason:  Client sent 'drop'
[AMXX] Authid "60" added to ban list
Writing banned.cfg.
```
banned.cfg shows :

`banid 0.0 UNKNOWN`

**Comment by SmileYzn** [comment]
Check what is the prameters for amx_ban or amx_addban, anyway here is the correct parameters:

server_cmd("amx_addban ^"%s"^ %i ^"Quitear MIX en curso no esta permitido^"",szAuth,iBanTime);

**Comment by illiaKuryaki** [comment]
Hi, amx_ban shows :

`Usage:  amx_ban <time in mins> <steamID or nickname or #authid or IP> <reason>`

and amx_addban :

`Usage:  amx_addban <"authid" or ip> <minutes> [reason]`

Problem is that i have amxbans, i want the bans to be on the mysql database, not in the banned.cfg, and it seems like amx_addban is doing only banned.cfg

**Comment by SmileYzn** [comment]
amx bans shoud be installed on server to work bro, i did not know what is your setup. What you need is only put the correct command and parameters at server_cmd line.
