### ISSUE TITLE
server so laggy when works so long time

### ISSUE THREAD

**Issue by wopox1337** [SmileYzn/PugMod-AMXX#17]
need to add into server.cfg ReHLDS CVar

- sv_rehlds_local_gametime 1

INFO: https://github.com/dreamstalker/rehlds/pull/287

as example you may check this server:
https://www.gametracker.com/server_info/91.202.247.219:27015/

**Comment by SmileYzn** [comment]
I think it is related with set_task in amxx, restarting map shoud fix it. But i will try to make hudlist without usage of set_task.


Ps. I need to fix to use with normal hlds and rehlds.

**Comment by wopox1337** [comment]
then, it is necessary to restart the map after some time, if it is empty

**Comment by SmileYzn** [comment]
Yes, i recomend you to restart every day or night when server is empty.
A just changelevel seems to fix it. Thanks for report this i still working in a new version improved for rehlds

👍 :+1:

**Comment by wopox1337** [comment]
why closed?

**Comment by wopox1337** [comment]
@SmileYzn why closed?

**Comment by SmileYzn** [comment]
As you said, sv_rehlds_local_gametime is a rehlds fix for that.
Also there is nothing i can do in plugin that fix these issue, since this is internal of HLDS / ReHLDS problem.

I need more tests in this new version, but for now i think that can't be fixed in mod.
