### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by Damigeana** [SmileYzn/PugMod-AMXX#19]
Metamod-r version 1.3.0.128 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `meta gpl' for details.
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:48 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70
[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '2117'
AMX Mod X version 1.8.2 Copyright (c) 2004-2006 AMX Mod X Development Team
AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
This is free software and you are welcome to redistribute it under
certain conditions; type 'amxx gpl' for details.
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugFlood.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugAdmin.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugCore.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugConfig.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugReady.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugMenus.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugWarmup.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugStats.amxx")
L 10/28/2020 - 20:41:48: [AMXX] Load error 17 (invalid file format or version) (plugin "PugVote.amxx")

**Comment by SmileYzn** [comment]
Check correct requisites to compile and run the PugMod.
