### ISSUE TITLE
Game with a 16-14 going to Overtime

### ISSUE THREAD

**Issue by JohnLOLTV** [SmileYzn/PugMod-AMXX#22]
My configs are:
pug_rounds_max		"30"
pug_rounds_ot		"4"
pug_force_ot		"1"

When the game regular time end in
CT:16
TR:14

The game forces de Overtime, and i dont know if a config error or a plugin error

Can you take a look plz?

**Comment by SmileYzn** [comment]
Did you just changed some cvar during game?
