### ISSUE TITLE
!pugstart, !forcestart, ... commands not found

### ISSUE THREAD

**Issue by Rookie001MC** [SmileYzn/PugMod-AMXX#23]
# Problem
Typing !pugstart in chat and in console gave the output of "Commands not found"

Tried to downgrade from latest (3.1.1) to 3.0.9, it still cannot find the command.

**Comment by SmileYzn** [comment]
PUG_RegCommand("startpug","PUG_StartPug",ADMIN_LEVEL_A,"PUG_DESC_START");	PUG_RegCommand("stoppug","PUG_StopPug",ADMIN_LEVEL_A,"PUG_DESC_STOP");
