### ISSUE TITLE
Add Captains Name to Hostname

### ISSUE THREAD

**Issue by dexter2486** [SmileYzn/PugMod-AMXX#24]
Can you add feature to it that the server name ie Hostname should be Like First Captain Name Vs Second Captain Name and also stats at the end of match like top frags, top deaths, bomb plants, match leavers etc.

**Comment by SmileYzn** [comment]
Yes it can be added, the problem is captains name in hostname heeheh.
Why you shoud use captain name in hostnames?

**Comment by dexter2486** [comment]
So that players can see that the match is live...or you can set hostname as Team CT(SCORE) :: TEAM T(SCORE)

**Comment by SmileYzn** [comment]
It can be done im game description also to not touch the hostname

**Comment by dexter2486** [comment]
ok kindly add the same with stats at the end of match like top frag player, top deaths player, most bomb plants by , total match leavers

**Comment by SmileYzn** [comment]
Stats of match are other part of pug
that need to be combined with csstats

You also can add csstats from default amxx installs.
Only terrible part is hud messages that statsx will generate in screen

**Comment by dracemix** [comment]
Cleverson tudo joia sou brasileiro amigo, estou a dias tentando um contato com voce te add steam estou precisando falar contigo,
jamais pensei que  o criador do pug era brasileiro hehe, enfim preciso falar contigo a respeito de projeto futuro como posso ter um contato mais proximo a voce ?
aguardo respostas

**Comment by SmileYzn** [comment]
Kk whatsapp 44991029928🙏

Em seg, 2 de ago de 2021 11:38, dracemix ***@***.***>
escreveu:
