### ISSUE TITLE
Add Github Actions for auto-build & auto-releases

### ISSUE THREAD

**Issue by wopox1337** [SmileYzn/PugMod-AMXX#25]
use this: https://github.com/marketplace/actions/setup-amxxpawn-compiler

Example:
- https://github.com/wopox1337/CSDM-ReAPI/blob/master/.github/workflows/CI.yml#L81-L105
- https://github.com/wopox1337/CSDM-ReAPI/actions/runs/1499336920 ([1](https://github.com/wopox1337/CSDM-ReAPI/runs/4311937137?check_suite_focus=true#step:9:1))

**Comment by SmileYzn** [comment]
The idea of current repo, is only store the code.
The releases i will do manually in a zip file. Since there are some library files, like .so or .dll.

Also is a custom amxmodx install, that only have the PugMod plugins.

**Comment by SmileYzn** [comment]
> use this: https://github.com/marketplace/actions/setup-amxxpawn-compiler
> 
> Example:
> 
> * https://github.com/wopox1337/CSDM-ReAPI/blob/master/.github/workflows/CI.yml#L81-L105
> * https://github.com/wopox1337/CSDM-ReAPI/actions/runs/1499336920 ([1](https://github.com/wopox1337/CSDM-ReAPI/runs/4311937137?check_suite_focus=true#step:9:1))

You can help to setup action? I can add you as maintainer.

**Comment by wopox1337** [comment]
@SmileYzn Yes, I can help you with that.
