### ISSUE TITLE
Translation not working in ".help" MOTD (v4.0.6)

### ISSUE THREAD

**Issue by Haco** [SmileYzn/PugMod-AMXX#37]
Hi, I don't know why but the translations for the saytext commands are missing in the ".help" MOTD.

I checked the language files, but the translations with the correct constatants are there. And every other translation of the PUG Mod is working, too. Maybe something code related.

![20220107135022_1](https://user-images.githubusercontent.com/3592977/148547226-132e4e58-256f-471f-9494-dd6c357438f5.jpg)

**Comment by SmileYzn** [comment]
Update Pug Mod to 4.0.6 and delete generated .html files in pug configuration directory.

This version fix generation of help command files.

Ps. Or just wait 4.0.7 that add pug_teams_enforcement_menu console variable :+1:
