### ISSUE TITLE
pugmod

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/PugMod-AMXX#42]
hello 

sir i need pugmod hlds 6153 version with autoready included.... and sir remove in game team changing.

**Comment by SmileYzn** [comment]
Check wiki for know what is the pug mod console variables and how to use them to control pug functionality. 
I do not provide support for ReHLDS installs or pugmod installs itself.

Also the pugmod need the user or administrator knowledge about HLDS installs, Counter-Strike variables and how ReHLDS + ReGameDLL_CS works and their variables too.

I just can't help if user has a specified problem or do not have a bit of knowledge about the mod.

**Comment by Escap3d** [comment]
How can i change the prifix name just like u add this mod pug start the me i want to change the pug name in this mod any option how can changw this (pug)..

**Comment by Escap3d** [comment]
Last one option i have an idea u dont mind it plzz add score board the match is end and player score total how muck kills death bomb plant every think

**Comment by gameinside** [comment]
> Last one option i have an idea u dont mind it plzz add score board the match is end and player score total how muck kills death bomb plant every think

change >scripting\include>PugCore.inc >  #define PUG_MOD_HEADER

**Comment by gameinside** [comment]
> How can i change the prifix name just like u add this mod pug start the me i want to change the pug name in this mod any option how can changw this (pug)..

change >scripting\include>PugCore.inc > #define PUG_MOD_HEADER

**Comment by Escap3d** [comment]
> > How can i change the prifix name just like u add this mod pug start the me i want to change the pug name in this mod any option how can changw this (pug)..
> 
> change >scripting\include>PugCore.inc > #define PUG_MOD_HEADER

not change bcs i change the name pug etc

**Comment by SmileYzn** [comment]
Make sure to change #define PUG_MOD_HEADER and recompile all plugins with changed includes too!

Ps. Please, also remove credits will help the project :rage:
