### ISSUE TITLE
Crash on first player joining

### ISSUE THREAD

**Issue by Crumar** [SmileYzn/PugMod-AMXX#44]
Hi,

just tried this out on fresh steamcmd DS install.
Copied over entire content of 4.0.8, and added my steamid in amxmodx users.ini and pug/admin.rc

I start with 
`/hlds_run -game cstrike -console +maxplayers 32 +map de_dust2 -secure -sv_lan 1 -autoupdate`
When I connect, server crashes with:
![image](https://user-images.githubusercontent.com/2611791/157846446-ff9b6875-9bd5-436a-97f7-4c0976248bea.png)

I have a seperate install dir with running amxmodx and w3ft, which starts fine.

This is running on debian bullseye

**Comment by Crumar** [comment]
Ah okay, only works with reHLDS. Pity

still, while amxx is running, no plugins are loaded
![image](https://user-images.githubusercontent.com/2611791/157851537-e5f2d975-74a5-4764-8767-2d80606a8627.png)

**Comment by SmileYzn** [comment]
I need to ask (Sorry for question) BUT:

"Copied over entire content of 4.0.8, and added my steamid in amxmodx users.ini and pug/admin.rc"

What content? from releases section or repository itself?

All Compiled files are only in Release Section. The repository have only source code.

**Comment by Crumar** [comment]
I copied addons / liblist / server.cfg from 4.0.8 release

**Comment by SmileYzn** [comment]
> I copied addons / liblist / server.cfg from 4.0.8 release

Did you tried to put a complete release in cstrike folder? It is just extract into cstrike.
Do not need to manually copy single files.

**Comment by Crumar** [comment]
Okay.
I did
Unzip to folder
cp -r folder/* hl/cstrike/
Metamod is running
Amxmodx is running
Plugins from pug are in amxmodx/plugins
Plugin.ini is same as in repository

I can retry with unzip directly in the folder but doubt that will change anything

**Comment by SmileYzn** [comment]
> Okay. I did Unzip to folder cp -r folder/* hl/cstrike/ Metamod is running Amxmodx is running Plugins from pug are in amxmodx/plugins Plugin.ini is same as in repository
> 
> I can retry with unzip directly in the folder but doubt that will change anything

I will never post any package that has this type of problem, this is tested under linux and windows without crash.

Did you tryed to unzip and run server?

**Comment by Crumar** [comment]
As mentioned above, the crash was due to me not using relhds. After adding rehlds, no crashes.
Didn't see this as a mandatory requirement from the readme/Wiki.

Did not try yet, will try this week

**Comment by SmileYzn** [comment]
Sorry :pray: 

I have adde to readme.md the requirements.
