### ISSUE TITLE
[bug] Votemap

### ISSUE THREAD

**Issue by EVOLCORE** [SmileYzn/PugMod-AMXX#8]
Map vote list doesn't show for ALL players, some players do not see any map list during vote at all.. it only appears 100% for everybody if nobody votes.. and then it goes into "insufficient votes" and brings menu back up again.

**Comment by shmileee** [comment]
Try asking your friends to set `setinfo "_vgui_menus" "0"`.

**Comment by SmileYzn** [comment]
> Map vote list doesn't show for ALL players, some players do not see any map list during vote at all.. it only appears 100% for everybody if nobody votes.. and then it goes into "insufficient votes" and brings menu back up again.

if some players open vgui buy menus when amxx menu is shown, this is a normal approach.
I need only to check if really vgui menu can be detected or not.
