### ISSUE TITLE
Load fails: Plugin file open error

### ISSUE THREAD

**Issue by smkerz** [SmileYzn/PugMod-AMXX#9]
Hello! Thank you for your plugin :)

But I have these errors with AMX Mod X version 1.8.3-dev+520

(  1) Load fails: Plugin file open error (plugin "PugFlood.amxx")
(  2) Load fails: Plugin file open error (plugin "PugAdmin.amxx")
(  3) Load fails: Plugin file open error (plugin "PugCore.amxx")
(  4) Load fails: Plugin file open error (plugin "PugConfig.amxx")
(  5) Load fails: Plugin file open error (plugin "PugReady.amxx")
(  6) Load fails: Plugin file open error (plugin "PugMenus.amxx")
(  7) Load fails: Plugin file open error (plugin "PugWarmup.amxx")
(  8) Load fails: Plugin file open error (plugin "PugStats.amxx")
(  9) Load fails: Plugin file open error (plugin "PugVote.amxx")

**Comment by smkerz** [comment]
I find the way to resolve that by compiling the .sma with Notepad++ on Windows with:
AMX 1.9 - build 5263 Base + Cstrike for Windows

And then upload the .amxx to the linux server with:
AMX 1.9 - build 5263 Base + Cstrike for Linux + PudMod GitHub archive

The files where download here: https://www.amxmodx.org/downloads-new.php

Also is it possible to unable the .hp command ?

Regards,

**Comment by SmileYzn** [comment]
Yes it needs amxx 1.10: https://github.com/SmileYzn/PugMod/blob/96680a46f3e4f50269ce6d690f1f18cb672967cb/addons/amxmodx/scripting/include/PugCore.inc#L12

About .hp command, did you want to disable? Comment the line: https://github.com/SmileYzn/PugMod/blob/96680a46f3e4f50269ce6d690f1f18cb672967cb/addons/amxmodx/scripting/PugStats.sma#L16

Ps. those commands are only for dead players until next round freeze time's end
